### ISSUE TITLE
Leaving server_id as null doesn't work

### ISSUE THREAD

**Issue by ReplicaObscura** [MrSuicideParrot/hassio-speedtest-addon#7]
The add-on settings can't currently be saved with the server_id set to null, which as I understand is the way for it to auto-select a server when it runs. The example configuration in the readme has null there, so it seems like this might be a UI or validation bug?

**Comment by ReplicaObscura** [comment]
Note that I ended up finding my correct server_id and using that instead since I don't actually want it to be random. I assumed that leaving the server_id off would do what SpeedTest.net does normally and choose the closest server automatically.

So while I don't need this add-on to support the null value anymore, it might make sense to either fix the behavior to match the documentation or fix the documentation to match the current behavior.

**Comment by MrSuicideParrot** [comment]
I think this issue is fixed in this latest release. 

Even though I defined the server_id variables has optional, the home-assistant forces that if we define its default value as null, the user must define it before running the addon and doesn't matter if the variable is optional or not. That was the bug....
